name: Compare Files and Generate Diff HTML

on:
  workflow_dispatch:  # allows manual triggering

jobs:
  compare-files:
    runs-on: self-hosted
    name: Compare comsapitnewpackage5.idmpck in Development and Test branches
    steps:
      - name: Checkout Development branch
        uses: actions/checkout@v3
        with:
          ref: Development
          path: dev_branch

      - name: Checkout Test branch
        uses: actions/checkout@v3
        with:
          ref: Test
          path: test_branch

      - name: Clean files by removing specified tags
        run: |
          TAGS="<MCSCRIPTSTATUS>|<TASKCHANGED>|<MCVERSION>|<ERRLOG>|<ERRFUNCTION>|<SNMPREMOTEHOST>"
          
          # Remove tags from Development branch file
          sed -E "s#</?($TAGS)>##g" dev_branch/comsapitnewpackage5.idmpck > dev_clean.txt
          
          # Remove tags from Test branch file
          sed -E "s#</?($TAGS)>##g" test_branch/comsapitnewpackage5.idmpck > test_clean.txt

      - name: Generate diff output as HTML
        run: |
          # Install diff2html-cli for HTML diff output
          npm install -g diff2html-cli
          
          # Generate unified diff file
          diff -u dev_clean.txt test_clean.txt > diff_output.diff || true
          
          # Convert diff to HTML
          diff2html -i file -s side -F diff_output.html diff_output.diff
          
          # Show generated file size
          ls -lh diff_output.html

      - name: Upload diff HTML artifact
        uses: actions/upload-artifact@v3
        with:
          name: diff-html-report
          path: diff_output.html
