name: Generate HTML Diff Between Branches
on:
  push:
    branches:
      - main  # Trigger only when pushing to the compare branch

jobs:
  html-diff:
    runs-on: [ linux ]
    env:
      BASE_BRANCH: Test
      COMPARE_BRANCH: Development
      FILE_PATH: comsapitnewpackage5.idmpck

    steps:
      - name: Checkout compare branch (Development)
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ env.COMPARE_BRANCH }}

      - name: Checkout base branch (Test)
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BASE_BRANCH }}
          path: base-branch
          fetch-depth: 1

      - name: Fetch file from base branch (Test)
        run: |
          cat base-branch/${FILE_PATH} > base.tmp
      - name: Copy compare branch file
        run: |
          cp $FILE_PATH compare.tmp
      - name: Clean files by removing specified XML-style tags
        run: |
          for tag in "PACKAGE_SCRIPTS" "CHANGED_DATE" "MCSCRIPTSTATUS" "TASKCHANGED" "MCVERSION" "ERRLOG" "ERRFUNCTION" "MCFROMREFERENCE" "SNMPREMOTEHOST"; do
            sed -i "/<${tag}>.*<\/${tag}>/d" base.tmp
            sed -i "/<${tag}\/>/d" base.tmp
            sed -i "/<${tag}>/d" base.tmp
            sed -i "/<\/${tag}>/d" base.tmp
            
            sed -i "/<${tag}>.*<\/${tag}>/d" compare.tmp
            sed -i "/<${tag}\/>/d" compare.tmp
            sed -i "/<${tag}>/d" compare.tmp
            sed -i "/<\/${tag}>/d" compare.tmp
          done
      - name: Generate diff.html via vimdiff
        run: |
          vimdiff base.tmp compare.tmp << 'EOF'
          :TOhtml
          :w! diff.html
          :qa!
          EOF
          sed -i 's/\.DiffAdd\s*{[^}]*}/.DiffAdd { background-color: #ccffcc; color: #000000; padding-bottom: 1px; }/' diff.html
          sed -i 's/\.DiffDelete\s*{[^}]*}/.DiffDelete { background-color: #ffcccc; color: #000000; padding-bottom: 1px; font-weight: bold; }/' diff.html
          sed -i 's/\.DiffChange\s*{[^}]*}/.DiffChange { background-color: #ffffcc; color: #000000; padding-bottom: 1px; }/' diff.html
          sed -i 's/\.DiffText\s*{[^}]*}/.DiffText { background-color: #ff6666; color: #000000; padding-bottom: 1px; font-weight: bold; }/' diff.html
      - name: Upload HTML diff
        uses: actions/upload-artifact@v3
        with:
          name: html-diff
          path: diff.html

name: Compare Files and Generate Diff HTML

on:
  workflow_dispatch:

jobs:
  compare-files:
    runs-on: self-hosted
    name: Compare comsapitnewpackage5.idmpck in Development and Test branches
    steps:
      - name: Checkout Development branch
        uses: actions/checkout@v3
        with:
          ref: Development
          path: dev_branch

      - name: Checkout Test branch
        uses: actions/checkout@v3
        with:
          ref: Test
          path: test_branch

      - name: Show files for debugging
        run: |
          echo "Development branch file content:"
          head -20 dev_branch/comsapitnewpackage5.idmpck || echo "File not found"
          echo "Test branch file content:"
          head -20 test_branch/comsapitnewpackage5.idmpck || echo "File not found"

      - name: Remove specified tags from files
        run: |
          # Tags to remove
          TAGS="MCSCRIPTSTATUS|TASKCHANGED|MCVERSION|ERRLOG|ERRFUNCTION|SNMPREMOTEHOST"

          # Remove tags including their closing tags (handle both opening and closing)
          sed -E "s#</?($TAGS)>##g" dev_branch/comsapitnewpackage5.idmpck > dev_clean.txt
          sed -E "s#</?($TAGS)>##g" test_branch/comsapitnewpackage5.idmpck > test_clean.txt

          echo "Cleaned Development file preview:"
          head -20 dev_clean.txt
          echo "Cleaned Test file preview:"
          head -20 test_clean.txt

      - name: Install diff2html-cli
        run: |
          if ! command -v npm > /dev/null; then
            echo "ERROR: npm is not installed. Please install nodejs and npm on runner."
            exit 1
          fi
          npm install -g diff2html-cli

      - name: Generate diff and convert to HTML
        run: |
          diff -u dev_clean.txt test_clean.txt > diff_output.diff || true
          echo "Diff file preview:"
          head -20 diff_output.diff || echo "Diff is empty"

          diff2html -i file -s side -F diff_output.html diff_output.diff
          echo "Generated HTML diff report:"
          ls -lh diff_output.html

      - name: Upload diff HTML artifact
        uses: actions/upload-artifact@v3
        with:
          name: diff-html-report
          path: diff_output.html
